### ISSUE TITLE
Updating from a previous version to the latest fails - migrations missing

### ISSUE THREAD

**Issue by creativedutchmen** [bashu/wagtail-embedvideos#43]
When updating my Wagtail installation from 1.6.2 to 1.9, I can no longer run migrations - causing the update to fail.

The reason for the failure is that the migrations (like 0003_auto_20150817_1256) are removed in the latest release, which causes problems because my models depend on these migrations.

**Comment by tiagofmc** [comment]
Hello @creativedutchmen,

When we made the change to remove the TagSearchable class from EmbedVideos, because it was removed on Wagtail 1.7, we didn't considered the change to be applied to projects that would be upgraded from 1.6 to 1.7 (upwards). Because of that, we removed all the migrations associated with Wagtail 1.6, and started a fresh new migration, that is compatible with Wagtail >=1.7.

If it's really urgent for you to upgrade to Wagtail 1.9 and you don't have any embed videos created, you could just `manage.py migrate wagtail_embed_videos zero` and then migrate to the recent version.

If you have embed videos created and you don't want them to erased, there is no current solution right now, unless using Wagtail 1.6.

We will try to fix this problem as soon as possible.

**Comment by creativedutchmen** [comment]
Yes, I understand the rationale behind the changes. However, upgrading between minor versions (1.x) is a very common use-case, so I can't imagine I'm the only one with this problem :)

Of course I could keep the current version of Wagtail, but the newer versions have features I'd really like to incorporate in the current project, so updating is certainly something I'd like to do sooner rather than later. (And, of course, there are many embed videos created).

I'd love to help, but I'm a bit short on time (as always). Would this be something you can fix within the next few weeks, or should I try to free some time for this?

**Comment by tiagofmc** [comment]
Well we are also very busy at the moment, but I will try to check it out as soon as possible.

Right now I can't establish a date for a fix, because I will probably do it whenever I have free time. But when I start making changes, I'm going to ref this issue, and you will know.

**Comment by SalahAdDin** [comment]
@tiagofmc What happened with this?

**Comment by gone** [comment]
Hey just to resurface this we just got bit pretty badly with this. NEVER delete migration files in a project used by other people as it borks the way django works pretty hard.

**Comment by DiogoMarques29** [comment]
Yes, that was a big mistake. Sorry guys.
